=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/new/Component.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Component">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="Description"/>
        <xs:element name="Models">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="DefaultModel">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="value"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="SpiceModel">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="value"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Netlists">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="QucsatorNetlist" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Include" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="value"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="value"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="NgspiceNetlist" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Include" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="value"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="value"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="CDLNetlist" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Include" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="value"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="value"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="XyceNetlist" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Include" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="value"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="value"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Symbols">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Symbol">
                <xs:complexType>
                  <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element name="PortSym">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:int" name="x"/>
                            <xs:attribute type="xs:int" name="y"/>
                            <xs:attribute type="xs:byte" name="type"/>
                            <xs:attribute type="xs:short" name="angle"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Line" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:int" name="x1"/>
                            <xs:attribute type="xs:int" name="y1"/>
                            <xs:attribute type="xs:int" name="x2"/>
                            <xs:attribute type="xs:int" name="y2"/>
                            <xs:attribute type="xs:string" name="color" use="optional"/>
                            <xs:attribute type="xs:int" name="width" use="optional"/>
                            <xs:attribute type="xs:byte" name="style" use="optional"/>
                            <xs:attribute type="xs:string" name="condition" use="optional" default=""/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Arc" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:int" name="x"/>
                            <xs:attribute type="xs:int" name="y"/>
                            <xs:attribute type="xs:int" name="arcWidth"/>
                            <xs:attribute type="xs:int" name="height"/>
                            <xs:attribute type="xs:int" name="angle"/>
                            <xs:attribute type="xs:int" name="len"/>
                            <xs:attribute type="xs:string" name="color" use="optional"/>
                            <xs:attribute type="xs:int" name="width" use="optional" default="2"/>
                            <xs:attribute type="xs:byte" name="style" use="optional" default="1"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                   </xs:choice>
                  <xs:attribute type="xs:string" name="id"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Parameters">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Parameter" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Description"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="name"/>
                  <xs:attribute type="xs:string" name="unit"/>
                  <xs:attribute type="xs:string" name="default_value" use="optional" default=""/>
                  <xs:attribute type="xs:string" name="equation" use="optional" default=""/>
                  <xs:attribute type="xs:boolean" name="show"/>
                  <xs:attribute type="xs:string" name="condition" use="optional" default=""/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="library"/>
      <xs:attribute type="xs:string" name="names"/>
      <xs:attribute type="xs:string" name="schematic_id"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/new/DIODE_IHP.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 131 BiCmos components" names="Diode" schematic_id = "D">
    <Description>
        Diode
    </Description>
    <Models>
        <DefaultModel value="D">
        </DefaultModel>
        <SpiceModel value="D">
        </SpiceModel>
    </Models>
    <Netlists>
    <NgspiceNetlist value = "{{{Letter}}}::schematic_id='nequal'D {nets} {model} {{W={W}}}::W='nonempty' {{L={L}}}::L='nonempty'"> </NgspiceNetlist>
        <CDLNetlist value = "{NgspiceNetlist}"> </CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/Diode.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="model" unit="" default_value="dantenna" show="true">
            <Description>[dantenna,dpantenna]modelname</Description>
        </Parameter>
        <Parameter name="Letter" unit="" default_value="X" show="false">
            <Description>[D,X]</Description>
        </Parameter>
        <Parameter name="W" unit="u" default_value="0.78" show="true">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="L" unit="u" default_value="0.78" show="true">
            <Description>Length</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/new/Cmim.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 131 BiCmos components" names="Cmim" schematic_id = "C">
    <Description>
        SG13G2 MiM capacitor
    </Description>
    <Models>
            <DefaultModel value="cmim">
            </DefaultModel>
            <SpiceModel value="cmim">
            </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value=
            "{{{Letter}}}::schematic_id='nequal'C{PartCounter} {nets} {C} M={m} {{{model}}}::model='nonempty'
            {{W={w}}}::w='nonempty' {{L={l}}}::l='nonempty'">
        </NgspiceNetlist>
        <CDLNetlist value="{NgspiceNetlist}"></CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
            <PortSym x="-30" y="0" type="1" angle="0" />
            <Line x1="-4" y1="-11" x2="-4" y2="11" color="#800000" width="2" style="1" />
            <Line x1="4" y1="-11" x2="4" y2="11" color="#800000" width="2" style="1" />
            <Line x1="-30" y1="0" x2="-4" y2="0" color="#000080" width="2" style="1" />
            <Line x1="4" y1="0" x2="30" y2="0" color="#000080" width="2" style="1" />
            <PortSym x="30" y="0" type="2" angle="127"/>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="model" unit="" default_value="cap_cmim" show="true">
            <Description>[cap_cmim,cparasitic,cap_rfcmin] modelname</Description>
        </Parameter>
        <Parameter name="Letter" unit="" default_value="X" show="false">
            <Description>C type</Description>
        </Parameter>
        <Parameter name="w" unit="um" default_value="10.0" show="true">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="l" unit="um" default_value="10.0" show="true">
            <Description>Length</Description>
        </Parameter>
        <Parameter name="m" unit="" default_value="1" show="true">
            <Description>multiplier</Description>
        </Parameter>
        <Parameter name="C" unit="F" equation="m*((w*l*1.e-3) + 2*(w+l)*40e-12)" show="true">
            <Description>Capacitance value</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/cmim.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="C" schematic_id = "cmim">
    <Description>
        SG13G2 MiM capacitor
    </Description>
    <Models>
            <DefaultModel value="cmim">
            </DefaultModel>
            <SpiceModel value="cmim">
            </SpiceModel>
    </Models>
    <Netlists>
            <NgspiceNetlist value ="">
                    <Include value="">
                    </Include>
            </NgspiceNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/Capacitor.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="w" unit="um" default_value="10.0" show="true">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="l" unit="um" default_value="10.0" show="true">
            <Description>Length</Description>
        </Parameter>
        <Parameter name="m" unit="" default_value="1" show="true">
            <Description>multiplier</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/ptap1.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="R" schematic_id = "ptap1">
    <Description>
        SG13G2 substrate tap resistor
    </Description>
    <Models>
        <DefaultModel value="ptap1">
        </DefaultModel>
        <SpiceModel value="ptap1">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value = 'XR{PartCounter} {nets} ptap1 w={w} l={l} m={m}'>
        </NgspiceNetlist>
        <CDLNetlist value = 'R{PartCounter} {nets} ptap1 w={w} l={l} m={m}'> </CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/Resistor.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="w" unit="um" default_value="0.78u" show="true">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="l" unit="um" default_value="0.78u" show="true">
            <Description>Length</Description>
        </Parameter>
        <Parameter name="m" unit="" default_value="1" show="true">
            <Description>multiplier</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/isolbox.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="dantenna" schematic_id = "D">
    <Description>
        SG13G2 isolation box 
    </Description>
    <Models>
        <DefaultModel value="isolbox">
        </DefaultModel>
        <SpiceModel value="D">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value = "{{{Letter}}}::schematic_id='nequal'D{PartCounter} {nets} {model} {{w={w}}}::w='nonempty' {{l={l}}}::l='nonempty'"> </NgspiceNetlist>
        <CDLNetlist value = "{NgspiceNetlist}"> </CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/IsolBox.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="model" unit="" default_value="dantenna" show="true">
            <Description>Modelname</Description>
        </Parameter>
        <Parameter name="Letter" unit="" default_value="X" show="false">
            <Description>Spice prefix</Description>
        </Parameter>
        <Parameter name="w" unit="u" default_value="3.0" show="true">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="l" unit="u" default_value="3.0" show="true">
            <Description>Length</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/npn13g2v.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="npn13g2v" schematic_id = "Q">
    <Description>
         SG13G2 high power HBT transistor
    </Description>
    <Models>
        <DefaultModel value="BJT_IHP">
        </DefaultModel>
        <SpiceModel value="npn13g2">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value=
            "{{{Letter}}}::schematic_id='nequal'Q{PartCounter} {nets} {{{model}}}::model='nonempty'
            {{Nx={Nx}}}::Nx='nonempty' {{El={El}}}::El='nonempty'">
        </NgspiceNetlist>
        <CDLNetlist value="{NgspiceNetlist}"></CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/Bjt.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="model" unit="" default_value="npn13g2v" show="true">
            <Description>Model name</Description>
        </Parameter>
        <Parameter name="Letter" unit="" default_value="X" show="false">
            <Description>Spice prefix</Description>
        </Parameter>
        <Parameter name="Nx" unit="" default_value="1" show="true">
            <Description>Number of emitters</Description>
        </Parameter>
        <Parameter name="El" unit="" default_value="" show="false">
            <Description>Emitter length</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/new/BJT_IHP.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 131 BiCmos components" names="npn13g2,npn13g2l,npn13g2v" schematic_id = "Q">
    <Description>
        Q(NPN) BJT
    </Description>
    <Models>
        <DefaultModel value="npn13g2">
        </DefaultModel>
        <SpiceModel value="npn13g2">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value=
            "{{{Letter}}}::schematic_id='nequal'Q{PartCounter} {nets} {{{model}}}::model='nonempty'
            {{Nx={Nx}}}::Nx='nonempty' {{El={El}}}::El='nonempty'">
        </NgspiceNetlist>
        <CDLNetlist value="{NgspiceNetlist}"></CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/Bjt.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="Letter" unit="" default_value="X" show="false">
            <Description>[Q,X] BJT type</Description>
        </Parameter>
        <Parameter name="model" unit="" default_value="npn13g2" show="true">
            <Description>[npn13g2,npn13g2l,npn13g2v]</Description>
        </Parameter>
        <Parameter name="model" unit="" default_value="npn13g2l" show="true" condition="name=npn13g2l">
            <Description>[npn13g2,npn13g2l,npn13g2v]</Description>
        </Parameter>
        <Parameter name="model" unit="" default_value="npn13g2v" show="true" condition="name=npn13g2v">
            <Description>[npn13g2,npn13g2l,npn13g2v]</Description>
        </Parameter>
        <Parameter name="Nx" unit="" default_value="1" show="true">
            <Description>Number of emitters</Description>
        </Parameter>
        <Parameter name="Nx" unit="" default_value="1" show="true" condition="name=ntap1,ptap1">
            <Description>Number of emitters</Description>
        </Parameter>
        <Parameter name="El" unit="" default_value="" show="false">
            <Description>Emitter length</Description>
        </Parameter>
        <Parameter name="El" unit="" default_value="1" show="true" condition="name=npn13g2l">
            <Description>Emitter length</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/ntap1.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="R" schematic_id = "ntap1">
    <Description>
        SG13G2 well tap resistor
    </Description>
    <Models>
        <DefaultModel value="ntap1">
        </DefaultModel>
        <SpiceModel value="ntap1">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value = 'XR{PartCounter} {nets} ntap1 w={w} l={l} m={m}'>
        </NgspiceNetlist>
        <CDLNetlist value = 'R{PartCounter} {nets} ntap1 w={w} l={l} m={m}'> </CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/Resistor.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="w" unit="um" default_value="0.78u" show="true">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="l" unit="um" default_value="0.78u" show="true">
            <Description>Length</Description>
        </Parameter>
        <Parameter name="m" unit="" default_value="1" show="true">
            <Description>multiplier</Description>
        </Parameter>
    </Parameters>
</Component>
