=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/new/Component.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Component">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="Description"/>
        <xs:element name="Models">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="DefaultModel">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="value"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="SpiceModel">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="value"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Netlists">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="QucsatorNetlist" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Include" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="value"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="value"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="NgspiceNetlist" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Include" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="value"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="value"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="CDLNetlist" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Include" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="value"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="value"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="XyceNetlist" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Include" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="value"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="value"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Symbols">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Symbol">
                <xs:complexType>
                  <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element name="PortSym">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:int" name="x"/>
                            <xs:attribute type="xs:int" name="y"/>
                            <xs:attribute type="xs:byte" name="type"/>
                            <xs:attribute type="xs:short" name="angle"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Line" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:int" name="x1"/>
                            <xs:attribute type="xs:int" name="y1"/>
                            <xs:attribute type="xs:int" name="x2"/>
                            <xs:attribute type="xs:int" name="y2"/>
                            <xs:attribute type="xs:string" name="color" use="optional"/>
                            <xs:attribute type="xs:int" name="width" use="optional"/>
                            <xs:attribute type="xs:byte" name="style" use="optional"/>
                            <xs:attribute type="xs:string" name="condition" use="optional" default=""/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Arc" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:int" name="x"/>
                            <xs:attribute type="xs:int" name="y"/>
                            <xs:attribute type="xs:int" name="arcWidth"/>
                            <xs:attribute type="xs:int" name="height"/>
                            <xs:attribute type="xs:int" name="angle"/>
                            <xs:attribute type="xs:int" name="len"/>
                            <xs:attribute type="xs:string" name="color" use="optional"/>
                            <xs:attribute type="xs:int" name="width" use="optional" default="2"/>
                            <xs:attribute type="xs:byte" name="style" use="optional" default="1"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                   </xs:choice>
                  <xs:attribute type="xs:string" name="id"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Parameters">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Parameter" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Description"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="name"/>
                  <xs:attribute type="xs:string" name="unit"/>
                  <xs:attribute type="xs:string" name="default_value" use="optional" default=""/>
                  <xs:attribute type="xs:string" name="equation" use="optional" default=""/>
                  <xs:attribute type="xs:boolean" name="show"/>
                  <xs:attribute type="xs:string" name="condition" use="optional" default=""/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="library"/>
      <xs:attribute type="xs:string" name="names"/>
      <xs:attribute type="xs:string" name="schematic_id"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/diodevdd_4kv.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="D" schematic_id = "diodevdd_4kv">
    <Description>
        SG13G2 ESD 4kV VDD diode
    </Description>
    <Models>
        <DefaultModel value="diodevdd_4kv">
        </DefaultModel>
        <SpiceModel value="diodevdd_4kv">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value = 'XD{PartCounter} {nets} diodevdd_4kv m={m}'></NgspiceNetlist>
        <CDLNetlist value = 'D{PartCounter} {nets} diodevdd_4kv m={m}'> </CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/diodevdd.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="m" unit="" default_value="1" show="true">
            <Description>multiplier</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/diodevss_2kv.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="D" schematic_id = "diodevss_2kv">
    <Description>
        SG13G2 ESD 2kV VSS diode
    </Description>
    <Models>
        <DefaultModel value="diodevss_2kv">
        </DefaultModel>
        <SpiceModel value="diodevss_2kv">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value = 'XD{PartCounter} {nets} diodevss_2kv m={m}'></NgspiceNetlist>
        <CDLNetlist value = 'D{PartCounter} {nets} diodevss_2kv m={m}'> </CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/diodevss.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="m" unit="" default_value="1" show="true">
            <Description>multiplier</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/new/MOS_IHP.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 131 BiCmos components" names="LV N-mos,HV N-mos,LV P-mos,HV P-mos" schematic_id = "M">
    <Description>
        4-pin MOS
    </Description>
    <Models>
        <DefaultModel value="npn13g2">
        </DefaultModel>
        <SpiceModel value="npn13g2">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value=
            "{{{Letter}}}::schematic_id='nequal'M{PartCounter} {nets} {{{model}}}::model='nonempty'
            {{W={W}}}::W='nonempty' {{L={L}}}::L='nonempty' {{ng={ng}}}::ng='nonempty' {{m={m}}}::m='nonempty'">
        </NgspiceNetlist>
        <CDLNetlist value="{NgspiceNetlist}"> </CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/Mos.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="Letter" unit="" default_value="X" show="false">
            <Description>SPICE letter</Description>
        </Parameter>
        <Parameter name="type" unit="" default_value="nmos" show="false">
            <Description>Channel type</Description>
        </Parameter>
        <Parameter name="type" unit="" default_value="pmos" show="false" condition="name=LV P-mos,HV P-mos">
            <Description>Channel type</Description>
        </Parameter>
        <Parameter name="model" unit="" default_value="sg13_lv_nmos" show="true">
            <Description>[sg13_lv_nmos,sg13_hv_nmos]</Description>
        </Parameter>
        <Parameter name="model" unit="" default_value="sg13_hv_nmos" show="true" condition="name=HV N-mos,HV P-mos">
            <Description>[sg13_lv_nmos,sg13_hv_nmos]</Description>
        </Parameter>
        <Parameter name="W" unit="" default_value="1u" show="true">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="L" unit="" default_value="1u" show="true">
            <Description>Length</Description>
        </Parameter>
        <Parameter name="ng" unit="" default_value="1" show="false">
            <Description>no. gates</Description>
        </Parameter>
        <Parameter name="m" unit="" default_value="1" show="false">
            <Description>no. devices</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/ACPowerSource.xml
<?xml version="1.0"?>
<Component
    xsi:noNamespaceSchemaLocation="Component.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    library="XML-based components" names="AC Power Source" schematic_id = "Pac">
    <Description>
        AC Power Source
    </Description>
    <Models>
        <DefaultModel value="Pac">
        </DefaultModel>
        <SpiceModel value="VP">
        </SpiceModel>
    </Models>
    <Netlists>
            <QucsatorNetlist value = 'Pac:P{PartCounter} {nets} Num="{PartCounter}" Z="{Z}" P="{P}" f="{f}" Temp="{Temp}"'>
            </QucsatorNetlist>
            <NgspiceNetlist value = 'VP{PartCounter} {nets} dc 0 ac {P} SIN(0 {P} {f}) portnum {NumPorts} z0 {Z}'>
            </NgspiceNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
            <PortSym x="0" y="30" type="1" angle="270" />
            <Line x1="11" y1="-22" x2="11" y2="22" color="#35322F" width="0" style="1" /> <!-- Outer box -->
            <Line x1="-11" y1="-22" x2="-11" y2="22" color="#35322F" width="0" style="1" />
            <Line x1="11" y1="-22" x2="-11" y2="-22" color="#35322F" width="0" style="1" />
            <Line x1="11" y1="22" x2="-11" y2="22" color="#35322F" width="0" style="1" />
            <Line x1="0" y1="30" x2="0" y2="19" color="#000080" width="2" style="1" />
            <Line x1="0" y1="-30" x2="0" y2="-19" color="#000080" width="2" style="1" />
            <Line x1="0" y1="1" x2="0" y2="-3" color="#000080" width="2" style="1" />
            <Line x1="5" y1="-3" x2="5" y2="-19" color="#000080" width="2" style="1" />
            <Line x1="-5" y1="-3" x2="-5" y2="-19" color="#000080" width="2" style="1" />
            <Line x1="5" y1="-3" x2="-5" y2="-3" color="#000080" width="2" style="1" />
            <Line x1="5" y1="-19" x2="-5" y2="-19" color="#000080" width="2" style="1" />
            <Arc x="-9" y="1" arcWidth="18" height="18" angle="0" len="5760" color="#000080" width="2" /> <!-- Circle -->
            <Arc x="-6" y="6" arcWidth="6" height="6" angle="0" len="2880" color="#000080" width="2" /> <!-- Half sine -->
            <Arc x="0" y="6" arcWidth="6" height="6" angle="2880" len="2880" color="#000080" width="2" /> <!-- The other half of the sine -->
            <Line x1="-5" y1="-25" x2="-11" y2="-25" color="#FF0000" width="1" style="1" /> <!-- Plus sign -->
            <Line x1="-8" y1="-28" x2="-8" y2="-22" color="#FF0000" width="1" style="1" />
            <Line x1="-5" y1="25" x2="-11" y2="25" color="#000000" width="1" style="1" /> <!-- Minus sign -->
            <PortSym x="0" y="-30" type="2" angle="90"/>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="NumPorts" unit="" default_value="1" show="true">
            <Description>Number of the port</Description>
        </Parameter>
        <Parameter name="Z" unit="Ohm" default_value="50" show="true">
            <Description>Port impedance</Description>
        </Parameter>
        <Parameter name="P" unit="dBm" default_value="0" show="true">
            <Description>(Available) AC power (dBm)</Description>
        </Parameter>
        <Parameter name="Vrms" unit="V" equation="sqrt(Z/1000.0)*10^(P/20)" show="true">
            <Description>RMS Voltage</Description>
        </Parameter>
        <Parameter name="Vpp" unit="V" equation="2.0*Vrms*sqrt(2.0)" show="false">
            <Description>Peak-to-Peak Voltage</Description>
        </Parameter>
        <Parameter name="f" unit="GHz" default_value="1" show="true">
            <Description>Frequency</Description>
        </Parameter>
        <Parameter name="Temp" unit="" default_value="26.85" show="false">
            <Description>Simulation temperature (C)</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/npn13G2l.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="Q" schematic_id = "npn13G2l">
    <Description>
        SG13G2 HBT transistor with configurable emmiter length
    </Description>
    <Models>
        <DefaultModel value="npn13G2l">
        </DefaultModel>
        <SpiceModel value="npn13G2l">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value = 'XQ{PartCounter} {nets} npn13G2l Nx={Nx} El={El}'>
        </NgspiceNetlist>
        <CDLNetlist value = 'Q{PartCounter} {nets} npn13G2l Nx={Nx}'> </CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/bjt.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="Nx" unit="" default_value="1" show="true">
            <Description>Number of emitters</Description>
        </Parameter>
        <Parameter name="El" unit="" default_value="2.5" show="true">
            <Description>Emitter length</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/sub.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="sub" schematic_id = "SUB">
    <Description>
        SG13G2 substrate tap resistor
    </Description>
    <Models>
        <DefaultModel value="SUB_IHP">
        </DefaultModel>
        <SpiceModel value="SUB">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value = ".GLOBAL {net} "> </NgspiceNetlist>
        <CDLNetlist value = "{NgspiceNetlist}"> </CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/sub.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="model" unit="" default_value="" show="true">
            <Description>Model name</Description>
        </Parameter>
        <Parameter name="net" unit="" default_value="sub!" show="false">
            <Description>Substrate net name</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/rhigh.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="R" schematic_id = "rhigh">
    <Description>
        SG13G2 high R resistor
    </Description>
    <Models>
        <DefaultModel value="rhigh">
        </DefaultModel>
        <SpiceModel value="rhigh">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value = 'XR{PartCounter} {nets} rhigh w={w} l={l} b={b} m={m}'></NgspiceNetlist>
        <CDLNetlist value = 'R{PartCounter} {nets} rhigh w={w} l={l} b={b} m={m}'> </CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/Resistor.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="w" unit="um" default_value="0.5" show="true">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="l" unit="um" default_value="0.5" show="true">
            <Description>Length</Description>
        </Parameter>
        <Parameter name="m" unit="" default_value="1" show="true">
            <Description>multiplier</Description>
        </Parameter>
        <Parameter name="b" unit="" default_value="0" show="true">
            <Description>Number of bends</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/rsil.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="R" schematic_id = "rsil">
    <Description>
        SG13G2 Salicide resistor
    </Description>
    <Models>
        <DefaultModel value="rsil">
        </DefaultModel>
        <SpiceModel value="rsil">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value = 'XR{PartCounter} {nets} rsil w={w} l={l} m={m}'>
        </NgspiceNetlist>
        <CDLNetlist value = 'R{PartCounter} {nets} rsil w={w} l={l} m={m}'> </CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/Resistor.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="w" unit="um" default_value="0.5" show="true">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="l" unit="um" default_value="0.5" show="true">
            <Description>Length</Description>
        </Parameter>
        <Parameter name="m" unit="" default_value="1" show="true">
            <Description>multiplier</Description>
        </Parameter>
    </Parameters>
</Component>
