=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/new/Component.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Component">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="Description"/>
        <xs:element name="Models">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="DefaultModel">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="value"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="SpiceModel">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="value"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Netlists">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="QucsatorNetlist" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Include" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="value"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="value"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="NgspiceNetlist" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Include" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="value"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="value"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="CDLNetlist" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Include" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="value"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="value"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="XyceNetlist" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Include" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="value"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="value"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Symbols">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Symbol">
                <xs:complexType>
                  <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element name="PortSym">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:int" name="x"/>
                            <xs:attribute type="xs:int" name="y"/>
                            <xs:attribute type="xs:byte" name="type"/>
                            <xs:attribute type="xs:short" name="angle"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Line" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:int" name="x1"/>
                            <xs:attribute type="xs:int" name="y1"/>
                            <xs:attribute type="xs:int" name="x2"/>
                            <xs:attribute type="xs:int" name="y2"/>
                            <xs:attribute type="xs:string" name="color" use="optional"/>
                            <xs:attribute type="xs:int" name="width" use="optional"/>
                            <xs:attribute type="xs:byte" name="style" use="optional"/>
                            <xs:attribute type="xs:string" name="condition" use="optional" default=""/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Arc" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:int" name="x"/>
                            <xs:attribute type="xs:int" name="y"/>
                            <xs:attribute type="xs:int" name="arcWidth"/>
                            <xs:attribute type="xs:int" name="height"/>
                            <xs:attribute type="xs:int" name="angle"/>
                            <xs:attribute type="xs:int" name="len"/>
                            <xs:attribute type="xs:string" name="color" use="optional"/>
                            <xs:attribute type="xs:int" name="width" use="optional" default="2"/>
                            <xs:attribute type="xs:byte" name="style" use="optional" default="1"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                   </xs:choice>
                  <xs:attribute type="xs:string" name="id"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Parameters">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Parameter" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Description"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="name"/>
                  <xs:attribute type="xs:string" name="unit"/>
                  <xs:attribute type="xs:string" name="default_value" use="optional" default=""/>
                  <xs:attribute type="xs:string" name="equation" use="optional" default=""/>
                  <xs:attribute type="xs:boolean" name="show"/>
                  <xs:attribute type="xs:string" name="condition" use="optional" default=""/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="library"/>
      <xs:attribute type="xs:string" name="names"/>
      <xs:attribute type="xs:string" name="schematic_id"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/dantenna.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="D" schematic_id = "dantenna">
    <Description>
        SG13G2 dantenna diode
    </Description>
    <Models>
        <DefaultModel value="dantenna">
        </DefaultModel>
        <SpiceModel value="dantenna">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value = 'XD{PartCounter} {nets} dantenna w={w} l={l} m={m}'></NgspiceNetlist>
        <CDLNetlist value = 'D{PartCounter} {nets} dantenna w={w} l={l} m={m}'> </CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/Diode.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="w" unit="um" default_value="0.78u" show="true">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="l" unit="um" default_value="0.78u" show="true">
            <Description>Length</Description>
        </Parameter>
        <Parameter name="m" unit="" default_value="1" show="true">
            <Description>multiplier</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/npn13G2.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="npn13g2" schematic_id = "Q">
    <Description>
        Q(NPN) BJT
    </Description>
    <Models>
        <DefaultModel value="npn13g2">
        </DefaultModel>
        <SpiceModel value="npn13g2">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value=
            "{{{Letter}}}::schematic_id='nequal'Q{PartCounter} {nets} {{{model}}}::model='nonempty'
            {{Nx={Nx}}}::Nx='nonempty' ">
        </NgspiceNetlist>
        <CDLNetlist value="{NgspiceNetlist}"></CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/Bjt.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="Letter" unit="" default_value="X" show="false">
            <Description>Spice prefix</Description>
        </Parameter>
        <Parameter name="model" unit="" default_value="npn13g2" show="true">
            <Description>npn13g2</Description>
        </Parameter>
        <Parameter name="Nx" unit="" default_value="1" show="true">
            <Description>Number of emitters</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/new/R_IHP.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 131 BiCmos components" names="rhigh,rsil,rppd,ptap1,ntap1" schematic_id = "R">
    <Description>
        SG13G2 resistor variant
    </Description>
    <Models>
        <DefaultModel value="R_IHP">
        </DefaultModel>
        <SpiceModel value="R">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value = "{{{Letter}}}::schematic_id='nequal'R{PartCounter} {nets} {R} {model} {{W={W}}}::W='nonempty' {{L={L}}}::L='nonempty'"> </NgspiceNetlist>
        <CDLNetlist value = "{NgspiceNetlist}"> </CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/Resistor.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="model" unit="" default_value="rhigh" show="true">
            <Description>[rsil,rppd,rhigh,ptap1,ntap1]</Description>
        </Parameter>
        <Parameter name="model" unit="" default_value="rsil" show="true" condition="name=rsil">
            <Description>[rsil,rppd,rhigh,ptap1,ntap1]</Description>
        </Parameter>
        <Parameter name="model" unit="" default_value="rppd" show="true" condition="name=rppd">
            <Description>[rsil,rppd,rhigh,ptap1,ntap1]</Description>
        </Parameter>
        <Parameter name="model" unit="" default_value="ptap1" show="true" condition="name=ptap1">
            <Description>[rsil,rppd,rhigh,ptap1,ntap1]</Description>
        </Parameter>
        <Parameter name="model" unit="" default_value="ntap1" show="true" condition="name=ntap1">
            <Description>[rsil,rppd,rhigh,ptap1,ntap1]</Description>
        </Parameter>
        <Parameter name="Letter" unit="" default_value="X" show="false">
            <Description>[R,X]</Description>
        </Parameter>
        <Parameter name="W" unit="um" default_value="0.5" show="true">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="W" unit="um" default_value="0.78" show="true" condition="name=ntap1,ptap1">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="L" unit="um" default_value="0.5" show="true">
            <Description>Length</Description>
        </Parameter>
        <Parameter name="L" unit="um" default_value="0.78" show="true" condition="name=ntap1,ptap1">
            <Description>Length</Description>
        </Parameter>
        <Parameter name="b" unit="" default_value="0" show="false" condition="name=rhigh,rsil,rppd">
            <Description>Number of bends</Description>
        </Parameter>
        <Parameter name="m" unit="" default_value="1" show="false" condition="name=rhigh,rsil,rppd">
            <Description>multiplier</Description>
        </Parameter>
        <Parameter name="R" unit="Ohm"
            equation="(1.6e-4 / W + 1360.0*((b + 1)*L + (1.081*(W - 0.04e-6) + 0.18e-6)*b) / (W - 0.04e-6)) / m"
            show="true" condition="name=rhigh">
            <Description>Resistance value</Description>
        </Parameter>
        <Parameter name="R" unit="Ohm"
            equation="(9.0e-6 / W + 7.0 * ((b + 1)*L + (1.081*(W + 1.0e-8) + 0.18e-6)*b) / (W + 1.0e-8)) / m"
            show="true" condition="name=rsil">
            <Description>Resistance value</Description>
        </Parameter>
        <Parameter name="R" unit="Ohm"
            equation="(70.0e-6 / W + 260.0 * ((b + 1)*L + (1.081*(W + 6.0e-9) + 0.18e-6)*b) / (W + 6.0e-9)) / m"
            show="true" condition="name=rppd">
            <Description>Resistance value</Description>
        </Parameter>
        <Parameter name="R" unit="Ohm"
            equation="1.0 / (1.0 / (9.8e-10 / (W * L)) + 1.0 / (9.8e-4 / (2.0 * (W + L))))"
            show="true" condition="name=ntap1,ptap1">
            <Description>Resistance value</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/rppd.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="R" schematic_id = "rppd">
    <Description>
        SG13G2 unsalicided resistor
    </Description>
    <Models>
        <DefaultModel value="rppd">
        </DefaultModel>
        <SpiceModel value="rppd">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value = 'XR{PartCounter} {nets} rppd w={w} l={l} b={b} m={m}'>
        </NgspiceNetlist>
        <CDLNetlist value = 'R{PartCounter} {nets} rppd w={w} l={l} b={b} m={m}'> </CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/Resistor.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="w" unit="um" default_value="0.5" show="true">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="l" unit="um" default_value="0.5" show="true">
            <Description>Length</Description>
        </Parameter>
        <Parameter name="m" unit="" default_value="1" show="true">
            <Description>multiplier</Description>
        </Parameter>
        <Parameter name="b" unit="" default_value="0" show="true">
            <Description>Number of bends</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/cap_rfcmim.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="cap_rfcmim" schematic_id = "C">
    <Description>
        SG13G2 RFMiM capacitor
    </Description>
    <Models>
            <DefaultModel value="C_IHP">
            </DefaultModel>
            <SpiceModel value="cmim">
            </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value=
            "{{{Letter}}}::schematic_id='nequal'C{PartCounter} {nets} {bulk} {{{model}}}::model='nonempty'
            {{w={w}}}::w='nonempty' {{l={l}}}::l='nonempty' wfeed={wfeed} ">
        </NgspiceNetlist>
        <CDLNetlist value="{NgspiceNetlist}"></CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
            <File>{QUCS_S_COMPONENTS_LIBRARY}/Capacitor.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="model" unit="" default_value="cap_rfcmim" show="true">
            <Description>Model name</Description>
        </Parameter>
        <Parameter name="Letter" unit="" default_value="X" show="false">
            <Description>Spice prefix</Description>
        </Parameter>
        <Parameter name="w" unit="u" default_value="10.0" show="true">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="l" unit="u" default_value="10.0" show="true">
            <Description>Length</Description>
        </Parameter>
        <Parameter name="bulk" unit="" default_value="sub!" show="false">
            <Description>Third terminal net name</Description>
        </Parameter>
        <Parameter name="wfeed" unit="um" default_value="5.0" show="true">
            <Description>Feed line length</Description>
        </Parameter>
        <Parameter name="C" unit="F" equation="m*((w*l*1.e-3) + 2*(w+l)*40e-12)" show="true">
            <Description>Capacitance value</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/sg13_lv_nmos.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="M" schematic_id = "sg13_lv_nmos">
    <Description>
        SG13G2 low voltage nmos transistor
    </Description>
    <Models>
        <DefaultModel value="sg13_lv_nmos">
        </DefaultModel>
        <SpiceModel value="sg13_lv_nmos">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value = 'XM{PartCounter} {nets} sg13_lv_nmos w={w} l={l} ng={ng} m={m}'>
        </NgspiceNetlist>
        <CDLNetlist value = 'M{PartCounter} {nets} sg13_lv_nmos w={w} l={l} ng={ng} m={m}'> </CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/nmos.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="w" unit="um" default_value="0.13" show="true">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="l" unit="um" default_value="0.13" show="true">
            <Description>Length</Description>
        </Parameter>
        <Parameter name="ng" unit="" default_value="1" show="true">
            <Description>Number of gates</Description>
        </Parameter>
        <Parameter name="m" unit="" default_value="1" show="true">
            <Description>multiplier</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/nmoscl_4.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="D" schematic_id = "nmoscl_4">
    <Description>
        SG13G2 nmoscl_4 mosfet clamps
    </Description>
    <Models>
        <DefaultModel value="nmoscl_4">
        </DefaultModel>
        <SpiceModel value="nmoscl_4">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value = 'XD{PartCounter} {nets} nmoscl_4 m={m}'></NgspiceNetlist>
        <CDLNetlist value = 'D{PartCounter} {nets} nmoscl_4 m={m}'> </CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/Diode.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="m" unit="" default_value="1" show="true">
            <Description>multiplier</Description>
        </Parameter>
    </Parameters>
</Component>

=== KrzysztofHerman/IHP-Open-PDK/ihp-sg13g2/libs.tech/qucs/symbols/pnpMPA.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 130 BiCMOS components" names="pnpMPA" schematic_id = "Q">
    <Description>
        SG13G2 pnpMPA
    </Description>
    <Models>
        <DefaultModel value="BJT_IHP">
        </DefaultModel>
        <SpiceModel value="pnpMPA">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value=
            "{{{Letter}}}::schematic_id='nequal'Q{PartCounter} {nets} {{{model}}}::model='nonempty'
            {{A={A}}}::A='nonempty' {{P={P}}}::P='nonempty'">
        </NgspiceNetlist>
        <CDLNetlist value="{NgspiceNetlist}"></CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/pnpMPA.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="model" unit="" default_value="pnpMPA" show="true">
            <Description>Model name</Description>
        </Parameter>
        <Parameter name="Letter" unit="" default_value="X" show="false">
            <Description>Spice prefix</Description>
        </Parameter>
        <Parameter name="w" unit="u" default_value="1.0" show="true">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="l" unit="u" default_value="2.0" show="true">
            <Description>Length</Description>
        </Parameter>
        <Parameter name="A" unit="" equation="w*l" show="false">
            <Description>Area</Description>
        </Parameter>
        <Parameter name="P" unit="" equation="2*(w+l)" show="false">
            <Description>Perimeter</Description>
        </Parameter>
        <Parameter name="m" unit="" default_value="1" show="false">
            <Description>Multiplier</Description>
        </Parameter>
    </Parameters>
</Component>
